sudo: required
services:
  - docker

before_install:
  - docker build -t achajackson/fiboapp-test -f ./client/Dockerfile.dev ./client

script:
  - docker run achajackson/fiboapp-test npm test -- --coverage

after_success:
  - docker build -t achajackson/app ./client
  - docker build -t achajackson/nginx ./nginx
  - docker build -t achajackson/server ./server
  - docker build -t achajackson/worker ./worker

#login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#push to Docker hub
  - docker push achajackson/app
  - docker push achajackson/nginx
  - docker push achajackson/server
  - docker push achajackson/worker