version: '3'
services:
  postgres:
    container_name: postgress
    image: 'postgres:latest'
  redis:
    container_name: redis
    image: 'redis:latest'
  nginx:
    container_name: nginx-server
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
   
  api:
    container_name: api
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /server/node_modules
      - ./server:/server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    container_name: client
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    container_name: worker
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /worker/node_modules
      - ./worker:/worker
