name: Build & publish multi docker images
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  #release:
   # types: [published]
  

env:
  REGISTRY: docker.io
  #IMAGE_NAME: ${{ fiboapp }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        IMAGE_NAME: [fiboapp]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWORD }}

#build the docker image
      - name: Build test docker image
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: dockerfile
          push: false
          tags: ${{secrets.DOCKER_ID}}/${{matrix.IMAGE_NAME}}-latest

#run test on image
#      - name: Run docker image
 #       uses: docker/docker-run-action@v3
  #      with:
   #       image: ${{secrets.DOCKER_ID}}/${{matrix.IMAGE_NAME}}-latest
  #       options: -v ${{ github.workspace }}:/work
   #       run: npm test -- --coverege

#build and push docker images
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: dockerfile
          push: true
          tags: ${{secrets.DOCKER_ID}}/${{matrix.IMAGE_NAME}}-app

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./nginx
          file: Dockerfile
          push: true
          tags: ${{secrets.DOCKER_ID}}/${{matrix.IMAGE_NAME}}-nginx
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: Dockerfile
          push: true
          tags: ${{secrets.DOCKER_ID}}/${{matrix.IMAGE_NAME}}-server

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./worker
          file: Dockerfile
          push: true
          tags: ${{secrets.DOCKER_ID}}/${{matrix.IMAGE_NAME}}-worker


